effects:
  owner:
    sound: 'ENTITY_PLAYER_LEVELUP'
    volume: 1.0
    pitch: 1.0
    lightning: true
    particle: 'HEART'
    number: 200 # Esto sería el número de partículas
    offsetX: 1 # Extensión en el eje X de la partícula
    offsetY: 1 # Extensión en el eje Y de la partícula
    offsetZ: 1 # Extensión en el eje Z de la partícula
    optionalvalue: 0.1 # Valor opcional que depende de cada partícula. En general significa "velocidad"

  admin:
    sound: 'ENTITY_FIREWORK_ROCKET_BLAST'
    volume: 0.8
    pitch: 1.2
    lightning: false
    particle: 'HEART'
    number: 200
    offsetX: 1
    offsetY: 1
    offsetZ: 1
    optionalvalue: 0.1

  dev:
    sound: 'ENTITY_PLAYER_LEVELUP'
    volume: 1.0
    pitch: 1.0
    lightning: false
    particle: 'HEART'
    number: 200
    offsetX: 1
    offsetY: 1
    offsetZ: 1
    optionalvalue: 0.1

  moderador:
    sound: 'ITEM_GOAT_HORN_SOUND_2'
    volume: 1.0
    pitch: 1.0
    lightning: false
    particle: 'HEART'
    number: 200
    offsetX: 1
    offsetY: 1
    offsetZ: 1
    optionalvalue: 0.1

  helper:
    sound: 'ITEM_GOAT_HORN_SOUND_4'
    volume: 0.9
    pitch: 1.1
    lightning: false
    particle: 'HEART'
    number: 200
    offsetX: 1
    offsetY: 1
    offsetZ: 1
    optionalvalue: 0.1

  builder:
    sound: 'ITEM_GOAT_HORN_SOUND_1'
    volume: 1.0
    pitch: 1.0
    lightning: false
    particle: 'HEART'
    number: 200
    offsetX: 1
    offsetY: 1
    offsetZ: 1
    optionalvalue: 0.1

  exodus:
    sound: 'ITEM_GOAT_HORN_SOUND_5'
    volume: 1.0
    pitch: 1.3
    lightning: true
    particle: 'HEART'
    number: 200
    offsetX: 1
    offsetY: 1
    offsetZ: 1
    optionalvalue: 0.1

  divine:
    sound: 'ENTITY_LIGHTNING_BOLT_THUNDER'
    volume: 1.0
    pitch: 1.0
    lightning: false
    particle: 'HEART'
    number: 200
    offsetX: 1
    offsetY: 1
    offsetZ: 1
    optionalvalue: 0.1

  nova:
    sound: 'ENTITY_FIREWORK_ROCKET_BLAST'
    volume: 1.0
    pitch: 1.0
    lightning: true
    particle: 'ELECTRIC_SPARK'
    number: 200
    offsetX: 1
    offsetY: 1
    offsetZ: 1
    optionalvalue: 0.1
